# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ['test']
  pull_request:
    branches: ['test']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo secrets
        env:
          owner: ${{secrets.owner}}
        run: |
          echo $owner
          echo $PATH
          echo $owner | sed 's/./& /g'
          echo $owner > owner.txt
          cat owner.txt
