# This is a workflow to help you auto update IC generated files to indicated package
name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'test'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # nodejs env
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: |
          npm -v
          node -v
      - name: Echo secrets
        env:
          owner: ${{secrets.owner}}
        run: |
          echo $owner
          echo $PATH
          echo $owner | sed 's/./& /g'
          echo $owner > owner.txt
          cat owner.txt
